class PrintText():

    def __init__(self, text):
        self.text = text.upper()
        self.dic = {
            '#' : b'\xe2\x96\x88'.decode('utf-8'),
            ' ' : ' '}
        self.characters = dict()
        
        temp = list()
        temp.append(self.decode(" "))
        temp.append(self.decode(" "))
        temp.append(self.decode(" "))
        temp.append(self.decode(" "))
        temp.append(self.decode(" "))
        self.characters.update({" ":temp})

        temp = list()
        temp.append(self.decode(" ###  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##### "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        self.characters.update({"A":temp})

        temp = list()
        temp.append(self.decode("####  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("####  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("####  "))
        self.characters.update({"B":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("##### "))
        self.characters.update({"C":temp})

        temp = list()
        temp.append(self.decode("####  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("####  "))
        self.characters.update({"D":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("####  "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("##### "))
        self.characters.update({"E":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("####  "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        self.characters.update({"F":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("# ### "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##### "))
        self.characters.update({"G":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##### "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        self.characters.update({"H":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("##### "))
        self.characters.update({"I":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("   #  "))
        temp.append(self.decode("   #  "))
        temp.append(self.decode("#  #  "))
        temp.append(self.decode("####  "))
        self.characters.update({"J":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#  #  "))
        temp.append(self.decode("###   "))
        temp.append(self.decode("#  #  "))
        temp.append(self.decode("#   # "))
        self.characters.update({"K":temp})

        temp = list()
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("##### "))
        self.characters.update({"L":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("## ## "))
        temp.append(self.decode("# # # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        self.characters.update({"M":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##  # "))
        temp.append(self.decode("# # # "))
        temp.append(self.decode("#  ## "))
        temp.append(self.decode("#   # "))
        self.characters.update({"N":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##### "))
        self.characters.update({"O":temp})

        temp = list()
        temp.append(self.decode("####  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("####  "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("#     "))
        self.characters.update({"P":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#  ## "))
        temp.append(self.decode("##### "))
        self.characters.update({"Q":temp})

        temp = list()
        temp.append(self.decode("####  "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("####  "))
        temp.append(self.decode("#  #  "))
        temp.append(self.decode("#   # "))
        self.characters.update({"R":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("#     "))
        temp.append(self.decode("##### "))
        temp.append(self.decode("    # "))
        temp.append(self.decode("##### "))
        self.characters.update({"S":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        self.characters.update({"T":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("##### "))
        self.characters.update({"U":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode(" # #  "))
        temp.append(self.decode("  #   "))
        self.characters.update({"V":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode("#   # "))
        temp.append(self.decode("# # # "))
        temp.append(self.decode("## ## "))
        temp.append(self.decode("#   # "))
        self.characters.update({"W":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode(" # #  "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode(" # #  "))
        temp.append(self.decode("#   # "))
        self.characters.update({"X":temp})

        temp = list()
        temp.append(self.decode("#   # "))
        temp.append(self.decode(" # #  "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode("  #   "))
        self.characters.update({"Y":temp})

        temp = list()
        temp.append(self.decode("##### "))
        temp.append(self.decode("   #  "))
        temp.append(self.decode("  #   "))
        temp.append(self.decode(" #    "))
        temp.append(self.decode("##### "))
        self.characters.update({"Z":temp})

        temp = list()
        temp.append(self.decode("# "))
        temp.append(self.decode("# "))
        temp.append(self.decode("# "))
        temp.append(self.decode("  "))
        temp.append(self.decode("# "))
        self.characters.update({"!":temp})

        temp = list()
        temp.append(self.decode("           ####                "))
        temp.append(self.decode("   ##    ############    ##    "))
        temp.append(self.decode("############################## "))
        temp.append(self.decode(" ############################  "))
        temp.append(self.decode("  ##########################   "))
        self.characters.update({"#":temp})

        temp = list()
        temp.append(self.decode("               #               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({"<":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("               #               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({">":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("               #               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({",":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("               #               "))
        temp.append(self.decode("                               "))
        self.characters.update({".":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("               #               "))
        self.characters.update({";":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({"?":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("             #####             "))
        self.characters.update({"$":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("           # # # # #           "))
        temp.append(self.decode("                               "))
        self.characters.update({"%":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("         #  #  #  #  #         "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({"^":temp})

        temp = list()
        temp.append(self.decode("                               "))
        temp.append(self.decode("     #    #    #    #    #     "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({"&":temp})

        temp = list()
        temp.append(self.decode("#       #      #       #      #"))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        temp.append(self.decode("                               "))
        self.characters.update({"*":temp})

    def __repr__(self):
        bigtext = ""
        for i in range(5):
            for l in self.text:
                bigtext += self.characters.get(l)[i]
            bigtext += '\n'
        return bigtext

    def decode(self, x):
        return (''.join(self.dic.get(i) for i in x))

